v0.3.1   * [optimization] `git clone` and `git pull` now use `--depth 1` to only get the latest     revision of `n`, which is all that is needed; tip of the hat to @steelbrain.

diff --git a/bin/n-install b/bin/n-install
--- a/bin/n-install
+++ b/bin/n-install
@@ -417,7 +417,7 @@ unset CDPATH  # to prevent unpredictable `cd` behavior
 [[ -t 1 ]] || kNO_COLOR=1 # turn off colored output if stdout is not connected to a terminal
 
 # Output version number and exit, if requested. Note that the `ver='...'` statement is automatically updated by `make version VER=<newVer>` - DO keep the 'v' suffix in the variable _definition_.
-[[ $1 == '--version' ]] && { ver='v0.3.0'; echo "$kTHIS_NAME ${ver#v}"$'\nFor license information and more, visit https://git.io/n-install-repo'; exit 0; }
+[[ $1 == '--version' ]] && { ver='v0.3.1'; echo "$kTHIS_NAME ${ver#v}"$'\nFor license information and more, visit https://git.io/n-install-repo'; exit 0; }
 
 # !! AS OF n 1.3.0, n ITSELF ONLY WORKS WITH curl, NOT ALSO WITH wget.
 # !! Once n also supports wget, mention wget as an alternative in the help text.
@@ -696,7 +696,7 @@ nBinDir=${N_PREFIX}/bin
 
 # Clone n's repository into "${N_PREFIX}/n/.repo"
 echo "-- Cloning $kN_REPO_URL to '$nRepoDir'..."
-git clone -q "$kN_REPO_URL" "$nRepoDir/" >/dev/null || die "Aborting, because cloning n's GitHub repository into '$nRepoDir' failed."
+git clone --depth 1 -q "$kN_REPO_URL" "$nRepoDir/" >/dev/null || die "Aborting, because cloning n's GitHub repository into '$nRepoDir' failed."
 
 echo "-- Running local n installation to '$nBinDir'..."
 (cd "$nRepoDir" && PREFIX="$N_PREFIX" "$makeExe" install >/dev/null) || die "Aborting, because n's own installation procedure failed."
